name: Deploy to GitHub Pages
permissions:
  contents: write

on:
  schedule:
    - cron: "0,30 * * * *" # 在每小时的00分和30分运行
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Ensure the workflow can push back to the repo
          persist-credentials: true
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run config converting script
        run: python src/main.py

      - name: Update changes
        run: |
          git add assets/final_config.json || true
          git commit -m "Update final_config.json" || echo "No changes to commit"
          git push origin HEAD:refs/heads/main || echo "Push failed"

      - name: Checkout Pages repository
        uses: actions/checkout@v4
        with:
          repository: cute-omega/cute-omega.github.io
          token: ${{ secrets.PAT }}
          path: pages-repo

      - name: Copy and commit to Pages repo
        run: |
          mkdir -p pages-repo/other-assets
          cp assets/final_config.json pages-repo/other-assets/ds-config.json
          cd pages-repo
          git add other-assets/ds-config.json || true
          git commit -m "Update ds-config.json to new location for permanent migration solution" || echo "No changes to commit"
          git push origin HEAD:refs/heads/main || echo "Push failed"
